
import java.awt.Color;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author GUI
 */
public class Menu_Principal extends javax.swing.JFrame {

    /**
     * Creates new form oi
     */
    public Menu_Principal() {
        initComponents();
        getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Retangulo_Borda = new javax.swing.JLabel();
        Botao_Sair = new javax.swing.JButton();
        Botao_Vendas = new javax.swing.JButton();
        Botao_Cliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Muda_cor(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens_Menu/Sem Título-2 1.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1064, 21, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens_Menu/Sem Título-2 2.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(982, 27, -1, -1));

        Retangulo_Borda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens_Menu/Rectangle 36.png"))); // NOI18N
        getContentPane().add(Retangulo_Borda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Botao_Sair.setBackground(new java.awt.Color(241, 241, 241));
        Botao_Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens_Menu/Botão Sair.png"))); // NOI18N
        Botao_Sair.setBorder(null);
        Botao_Sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Botao_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_SairActionPerformed(evt);
            }
        });
        getContentPane().add(Botao_Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1113, 698, -1, -1));

        Botao_Vendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens_Menu/Botão Vendas.png"))); // NOI18N
        Botao_Vendas.setBorder(null);
        Botao_Vendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Botao_Vendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_VendasActionPerformed(evt);
            }
        });
        getContentPane().add(Botao_Vendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 307, -1, -1));

        Botao_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens_Menu/Botão Clientes.png"))); // NOI18N
        Botao_Cliente.setBorderPainted(false);
        Botao_Cliente.setContentAreaFilled(false);
        Botao_Cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Botao_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_ClienteActionPerformed(evt);
            }
        });
        getContentPane().add(Botao_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 300, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens_Menu/Senhor Acai.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(929, 246, -1, -1));

        setSize(new java.awt.Dimension(1456, 1032));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Muda_cor(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Muda_cor

    }//GEN-LAST:event_Muda_cor

    private void Botao_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Botao_SairActionPerformed

    private void Botao_VendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_VendasActionPerformed
        new Tela_Vendas().setVisible(true);
        dispose();
    }//GEN-LAST:event_Botao_VendasActionPerformed

    private void Botao_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_ClienteActionPerformed
        new Tela_Cliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_Botao_ClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao_Cliente;
    private javax.swing.JButton Botao_Sair;
    private javax.swing.JButton Botao_Vendas;
    private javax.swing.JLabel Retangulo_Borda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
